### ISSUE TITLE
Problem in local.

### ISSUE THREAD

**Issue by jabrena** [tgirotto/ustmarketplace#11]
Hi,

I have tried to run in local the project, but I receive the following error:

``` javascript

➜  marketplace git:(master) node app.js     
module.js:338
    throw err;
          ^
Error: Cannot find module 'connect-busboy'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jabrena/Documents/DATA/2015/RESEARCH/internet/nodejs/marketplace/app.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

```

Note: I have installed packages described in package.json with sudo npm install.

Many thanks in advance

**Comment by jabrena** [comment]
Fixed.

Please, update package.json with this dependency:

npm install connect-busboy --save
